name: Deploy Library Website
on:
  push:
    branches:
      - -main
permissions: 
   contents: read
   pages: write
   id-token: write
jobs:
  deploy:
  runs-on: ubuntu-latest
  environment:
  name: github-pages
  url: $
  {{ steps.deployments.outputs.page-url}}
  steps:
  -name: Get the code
  uses:
  actions/checkout@v6
  -name: Upload website
  uses:
  actions/configure-pages@v5
  -name: Upload website
  uses:
  actions/upload-pages-artifact@v4
  with:
  path: '.'
  -name: Deploy website
  id: deployment
  uses
  actions/deploy-pages@v4
      
